const mongoose = require('mongoose');

const recordSchema = new mongoose.Schema({
  Study_ID: { type: String, required: true },
  Patient_ID: { type: String, required: true },
  Sample_ID: { type: String, required: true },
  Diagnosis_Age: { type: Number, required: true },
  American_Joint_Committee_on_Cancer_Publication_Version_Type: { type: String },
  Biopsy_Site: { type: String },
  Cancer_Type: { type: String, required: true },
  Cancer_Type_Detailed: { type: String },
  Disease_Free_Months: { type: String },
  Disease_Free_Status: { type: String },
  Disease_Type: { type: String },
  Ethnicity_Category: { type: String },
  Fraction_Genome_Altered: { type: Number },
  ICD_10_Classification: { type: String },
  Is_FFPE: { type: String },
  Morphology: { type: String },
  Mutation_Count: { type: Number },
  Oncotree_Code: { type: String },
  Overall_Survival_Months: { type: Number },
  Overall_Survival_Status: { type: String },
  Other_Patient_ID: { type: String },
  Other_Sample_ID: { type: String },
  AJCC_Pathologic_M_Stage: { type: String },
  AJCC_Pathologic_N_Stage: { type: String },
  AJCC_Pathologic_Stage: { type: String },
  AJCC_Pathologic_T_Stage: { type: String },
  Primary_Diagnosis: { type: String },
  Patient_Primary_Tumor_Site: { type: String },
  Prior_Malignancy: { type: Boolean },
  Prior_Treatment: { type: Boolean },
  Project_Identifier: { type: String },
  Project_Name: { type: String },
  Project_State: { type: String },
  Race_Category: { type: String },
  Number_of_Samples_Per_Patient: { type: Number },
  Sample_Type: { type: String },
  Sex: { type: String },
  Years_Smoked: { type: String },
  Person_Cigarette_Smoking_History_Pack_Year_Value: { type: Number },
  Patients_Vital_Status: { type: String },
  Year_of_Death: { type: String },
  Year_of_Diagnosis: { type: Number }
});

const Record = mongoose.model('Record', recordSchema);
export default Record;
